{% set name = "jasp" %}
{% set version = "0.15.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/jasp-stats/jasp-desktop/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2f230cfb51f1515fe9bc7153cc8d0699a86125e7445400f574094130cb112cd6

build:
  number: 0
  ## windows and osx builds can be added later, I currently don't have either for local testing
  skip: true  # [not linux]
  rpaths:
    - lib/
    - lib/R/lib/
    - lib/R/library/Rcpp/libs/
    - lib/R/library/RInside/lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]
    - make
    - sed
    - rsync
    - coreutils
    - pkg-config
    - {{ cdt('expat-devel') }}  # [linux]
    - {{ cdt('libxfixes-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxdamage-devel') }}  # [linux]    
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxxf86vm-devel') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxau') }}  # [linux]
    - {{ cdt('libxscrnsaver') }}  # [linux]
    - {{ cdt('libxscrnsaver-devel') }}  # [linux]
    - {{ cdt('libxcomposite') }}  # [linux]
    - {{ cdt('libxcomposite-devel') }}  # [linux]
    - {{ cdt('libxi') }}  # [linux]
    - {{ cdt('libxi-devel') }}  # [linux]
    - {{ cdt('libxtst') }}  # [linux]
    - {{ cdt('libxtst-devel') }}  # [linux]
    - {{ cdt('pciutils-devel') }}  # [linux]
    - {{ cdt('pciutils-libs') }}  # [linux]
    - {{ cdt('libxcursor-devel') }}  # [linux]
    - {{ cdt('libxcursor') }}  # [linux]
  host:
    ## shouldn't need this in host, but can't find libGL.so otherwise
    - {{ cdt('mesa-libgl-devel') }}  # [linux]    
    - expat  # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxdamage  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxcb  # [linux]
    - xorg-libxau  # [linux]
    - xorg-libxscrnsaver  # [linux]
    - xorg-libxcomposite  # [linux]
    - xorg-libxi  # [linux]
    - xorg-libxtst  # [linux]
    - xorg-libxcursor  # [linux]
    - boost
    - boost-cpp
    - libarchive
    - tk
    - qt
    - zlib
    - readstat
    - r-base
    - r-bh
    - r-r6
    - r-devtools
    - r-ggplot2
    - r-gridextra
    - r-gtable
    - r-jsonlite
    - r-rcolorbrewer
    - r-rlang
    - r-scales
    - r-stringr
    - r-viridislite
    - r-rcpp
    - r-rinside
    - r-kknn
    ## these have to be installed at build time to prevent jasp from installing them from CRAN
    - r-abind
    - r-abtest
    - r-afex
    - r-arm
    - r-askpass
    - r-backports
    - r-bas
    - r-base
    - r-base64enc
    - r-bayesfactor
    - r-bayesplot
    - r-bh
    - r-bit
    - r-bit64
    - r-bms
    - r-boot
    - r-brew
    - r-brio
    - r-broom
    - r-bslib
    - r-bstats
    - r-ca
    - r-cachem
    - r-callr
    - r-car
    - r-cardata
    - r-cellranger
    - r-checkmate
    - r-class
    - r-cli
    - r-clipr
    - r-cluster
    - r-coda
    - r-codetools
    - r-colorspace
    - r-colourpicker
    - r-commonmark
    - r-conquer
    - r-contfrac
    - r-conting
    - r-corpcor
    - r-cpp11
    - r-crayon
    - r-credentials
    - r-crosstalk
    - r-curl
    - r-data.table
    - r-desc
    - r-desolve
    - r-devtools
    - r-diffobj
    - r-digest
    - r-doparallel
    - r-dplyr
    - r-dt
    - r-dygraphs
    - r-ellipsis
    - r-elliptic
    - r-emmeans
    - r-estimability
    - r-evaluate
    - r-fansi
    - r-farver
    - r-fastmap
    - r-fdrtool
    - r-forcats
    - r-foreach
    - r-foreign
    - r-formula
    - r-fs
    - r-gdtools
    - r-generics
    - r-gert
    - r-ggplot2
    - r-ggpol
    - r-ggrepel
    - r-ggridges
    - r-gh
    - r-gitcreds
    - r-glasso
    - r-glue
    - r-gnm
    - r-gparotation
    - r-gridextra
    - r-gridgraphics
    - r-gtable
    - r-gtools
    - r-haven
    - r-highr
    - r-hmeasure
    - r-hmisc
    - r-hms
    - r-htmltable
    - r-htmltools
    - r-htmlwidgets
    - r-httpuv
    - r-httr
    - r-hypergeo
    - r-igraph
    - r-ini
    - r-inline
    - r-isoband
    - r-iterators
    - r-jpeg
    - r-jquerylib
    - r-jsonlite
    - r-kernsmooth
    - r-knitr
    - r-kutils
    - r-labeling
    - r-later
    - r-lattice
    - r-latticeextra
    - r-lavaan
    - r-lazyeval
    - r-lifecycle
    - r-lisreltor
    - r-lme4
    - r-lmertest
    - r-lmtest
    - r-logspline
    - r-loo
    - r-magrittr
    - r-maptools
    - r-markdown
    - r-mass
    - r-matrix
    - r-matrixcalc
    - r-matrixmodels
    - r-matrixstats
    - r-mdscore
    - r-memoise
    - r-mgcv
    - r-mi
    - r-mime
    - r-miniui
    - r-minqa
    - r-mnormt
    - r-modules
    - r-moments
    - r-multcomp
    - r-munsell
    - r-mvtnorm
    - r-nlme
    - r-nloptr
    - r-nnet
    - r-nortest
    - r-numderiv
    - r-officer
    - r-onewaytests
    - r-openmx
    - r-openssl
    - r-openxlsx
    - r-packrat
    - r-pbapply
    - r-pbivnorm
    - r-pbkrtest
    - r-pillar
    - r-pkgbuild
    - r-pkgconfig
    - r-pkgload
    - r-plotrix
    - r-plyr
    - r-png
    - r-ppcor
    - r-praise
    - r-prettyunits
    - r-processx
    - r-progress
    - r-promises
    - r-ps
    - r-psych
    - r-purrr
    - r-qgam
    - r-qgraph
    - r-quadprog
    - r-quantmod
    - r-quantreg
    - r-qvcalc
    - r-r6
    - r-ragg
    - r-rappdirs
    - r-rcmdcheck
    - r-rcolorbrewer
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppeigen
    - r-rcppparallel
    - r-rcsdp
    - r-readr
    - r-readxl
    - r-regsem
    - r-relimp
    - r-rematch
    - r-rematch2
    - r-remotes
    - r-renv
    - r-reshape2
    - r-rio
    - r-rjson
    - r-rlang
    - r-rockchalk
    - r-roxygen2
    - r-rpart
    - r-rpf
    - r-rprojroot
    - r-rsconnect
    - r-rsolnp
    - r-rstan
    - r-rstanarm
    - r-rstantools
    - r-rstudioapi
    - r-runit
    - r-rversions
    - r-rvg
    - r-sandwich
    - r-sass
    - r-scales
    - r-sem
    - r-semplot
    - r-semtools
    - r-sessioninfo
    - r-shiny
    - r-shinyjs
    - r-shinystan
    - r-shinythemes
    - r-sn
    - r-sourcetools
    - r-sp
    - r-sparsem
    - r-spatial
    - r-stanheaders
    - r-stanova
    - r-stringi
    - r-stringr
    - r-suppdists
    - r-survival
    - r-svglite
    - r-sys
    - r-systemfonts
    - r-testthat
    - r-textshaping
    - r-th.data
    - r-threejs
    - r-tibble
    - r-tidyr
    - r-tidyselect
    - r-tmvnsim
    - r-truncnorm
    - r-tseries
    - r-ttr
    - r-tzdb
    - r-usethis
    - r-utf8
    - r-uuid
    - r-v8
    - r-vcd
    - r-vcdextra
    - r-vctrs
    - r-viridis
    - r-viridislite
    - r-vroom
    - r-waldo
    - r-whisker
    - r-withr
    - r-xfun
    - r-xml
    - r-xml2
    - r-xopen
    - r-xtable
    - r-xts
    - r-yaml
    - r-zip
    - r-zoo
  run:
    - boost
    - boost-cpp
    - zlib
    - readstat
    - r-abind
    - r-abtest
    - r-afex
    - r-arm
    - r-askpass
    - r-backports
    - r-bas
    - r-base
    - r-base64enc
    - r-bayesfactor
    - r-bayesplot
    - r-bh
    - r-bit
    - r-bit64
    - r-bms
    - r-boot
    - r-brew
    - r-brio
    - r-broom
    - r-bslib
    - r-bstats
    - r-ca
    - r-cachem
    - r-callr
    - r-car
    - r-cardata
    - r-cellranger
    - r-checkmate
    - r-class
    - r-cli
    - r-clipr
    - r-cluster
    - r-coda
    - r-codetools
    - r-colorspace
    - r-colourpicker
    - r-commonmark
    - r-conquer
    - r-contfrac
    - r-conting
    - r-corpcor
    - r-cpp11
    - r-crayon
    - r-credentials
    - r-crosstalk
    - r-curl
    - r-data.table
    - r-desc
    - r-desolve
    - r-devtools
    - r-diffobj
    - r-digest
    - r-doparallel
    - r-dplyr
    - r-dt
    - r-dygraphs
    - r-ellipsis
    - r-elliptic
    - r-emmeans
    - r-estimability
    - r-evaluate
    - r-fansi
    - r-farver
    - r-fastmap
    - r-fdrtool
    - r-forcats
    - r-foreach
    - r-foreign
    - r-formula
    - r-fs
    - r-gdtools
    - r-generics
    - r-gert
    - r-ggplot2
    - r-ggpol
    - r-ggrepel
    - r-ggridges
    - r-gh
    - r-gitcreds
    - r-glasso
    - r-glue
    - r-gnm
    - r-gparotation
    - r-gridextra
    - r-gridgraphics
    - r-gtable
    - r-gtools
    - r-haven
    - r-highr
    - r-hmeasure
    - r-hmisc
    - r-hms
    - r-htmltable
    - r-htmltools
    - r-htmlwidgets
    - r-httpuv
    - r-httr
    - r-hypergeo
    - r-igraph
    - r-ini
    - r-inline
    - r-isoband
    - r-iterators
    - r-jpeg
    - r-jquerylib
    - r-jsonlite
    - r-kernsmooth
    - r-knitr
    - r-kutils
    - r-labeling
    - r-later
    - r-lattice
    - r-latticeextra
    - r-lavaan
    - r-lazyeval
    - r-lifecycle
    - r-lisreltor
    - r-lme4
    - r-lmertest
    - r-lmtest
    - r-logspline
    - r-loo
    - r-magrittr
    - r-maptools
    - r-markdown
    - r-mass
    - r-matrix
    - r-matrixcalc
    - r-matrixmodels
    - r-matrixstats
    - r-mdscore
    - r-memoise
    - r-mgcv
    - r-mi
    - r-mime
    - r-miniui
    - r-minqa
    - r-mnormt
    - r-modules
    - r-moments
    - r-multcomp
    - r-munsell
    - r-mvtnorm
    - r-nlme
    - r-nloptr
    - r-nnet
    - r-nortest
    - r-numderiv
    - r-officer
    - r-onewaytests
    - r-openmx
    - r-openssl
    - r-openxlsx
    - r-packrat
    - r-pbapply
    - r-pbivnorm
    - r-pbkrtest
    - r-pillar
    - r-pkgbuild
    - r-pkgconfig
    - r-pkgload
    - r-plotrix
    - r-plyr
    - r-png
    - r-ppcor
    - r-praise
    - r-prettyunits
    - r-processx
    - r-progress
    - r-promises
    - r-ps
    - r-psych
    - r-purrr
    - r-qgam
    - r-qgraph
    - r-quadprog
    - r-quantmod
    - r-quantreg
    - r-qvcalc
    - r-r6
    - r-ragg
    - r-rappdirs
    - r-rcmdcheck
    - r-rcolorbrewer
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppeigen
    - r-rcppparallel
    - r-rcsdp
    - r-readr
    - r-readxl
    - r-regsem
    - r-relimp
    - r-rematch
    - r-rematch2
    - r-remotes
    - r-renv
    - r-reshape2
    - r-rio
    - r-rjson
    - r-rlang
    - r-rockchalk
    - r-roxygen2
    - r-rpart
    - r-rpf
    - r-rprojroot
    - r-rsconnect
    - r-rsolnp
    - r-rstan
    - r-rstanarm
    - r-rstantools
    - r-rstudioapi
    - r-runit
    - r-rversions
    - r-rvg
    - r-sandwich
    - r-sass
    - r-scales
    - r-sem
    - r-semplot
    - r-semtools
    - r-sessioninfo
    - r-shiny
    - r-shinyjs
    - r-shinystan
    - r-shinythemes
    - r-sn
    - r-sourcetools
    - r-sp
    - r-sparsem
    - r-spatial
    - r-stanheaders
    - r-stanova
    - r-stringi
    - r-stringr
    - r-suppdists
    - r-survival
    - r-svglite
    - r-sys
    - r-systemfonts
    - r-testthat
    - r-textshaping
    - r-th.data
    - r-threejs
    - r-tibble
    - r-tidyr
    - r-tidyselect
    - r-tmvnsim
    - r-truncnorm
    - r-tseries
    - r-ttr
    - r-tzdb
    - r-usethis
    - r-utf8
    - r-uuid
    - r-v8
    - r-vcd
    - r-vcdextra
    - r-vctrs
    - r-viridis
    - r-viridislite
    - r-vroom
    - r-waldo
    - r-whisker
    - r-withr
    - r-xfun
    - r-xml
    - r-xml2
    - r-xopen
    - r-xtable
    - r-xts
    - r-yaml
    - r-zip
    - r-zoo

test:
  commands:
    - test -f $PREFIX/bin/jasp

about:
  home: http://jasp-stats.org/
  license: AGPL-3.0-only
  license_file: COPYING.txt
  summary: A fresh way to do statistics

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
    - Naeemkh
